In [ ]:
print("twinkle twinkle little star", "\n", "\t", "how i wonder what you are", "\n", "\t", "\t",
     "Up above the world so high", "\n" ,"\t", "\t",
      "Like a diamond in the sky.", "\n" ,
"Twinkle, twinkle, little star", "\n" , "\t",
"How I wonder what you are")

In [ ]:
#python version and version info
#sys module gives access to variable and functions that intract with interpretor

import sys
print("Python version")
print(sys.version)
print("version_Info")
print(sys.version_info)

In [1]:
#current date and time
import datetime
today = datetime.datetime.now()
print("today's date and time are: ", "\n")
print(today.strftime("%Y-%m-%d , %H:%M:%S"))

today's date and time are:  

2020-06-29 , 15:12:59


In [ ]:
r = float(input ("Input the radius of the circle : "))
area = str(3.14 * r**2)
print ("The area of the circle with radius " , str(r) , " is: " , str(area))


In [ ]:
nl = []
for i in range(1500,2071):
    if(i%7 == 0) and (i%5 == 0):
        nl.append(i)
print(nl)

In [ ]:
celcius = float(input("Enter temp in celcius"))
faren  = float(input("Enter temp in farenhiet"))
temp = 
if()

In [1]:
for i in range(5):
    for j in range(i+1):
        print("*" , end =" ")
    print('')  
for i in range(4):
    for j in range(4-i):
        print("*", end = " ")
    print('')    

* 
* * 
* * * 
* * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


In [ ]:
word = input('Enter a word to reverse ->')

for value in range(len(word) -1,-1,-1):
    print(word[value], end = " ")

In [ ]:
#???????????????????????????????????????????????????????to take 2 or 3 digit numbers also

count_even = 0
count_odd =0
numbers = input("Enter the String of numbers:")
for i in range(len(numbers)):
    if i % 2 == 0:                                       #x % y (x wrt to y)
        count_even += 1
    else:
        count_odd += 1
        
print("Number of even numbers are ->", count_even)
print("Number of odd numbers are ->", count_odd)
      
    

In [ ]:
datalist = [1452, 11.23, 1+2j, True, 'w3resource', (0, -1), [5, 12], {"class":'V', "section":'A'}]
for values in datalist:
    print(" The type of", values, "is", type(values))

In [ ]:
for i in range(10):
    if (i == 3 or i ==6):
        pass                  #continue statement returns the control again at the top of the loop
    print(i, end = " ")       

In [1]:
#palindrome
x,y = 0,1

while y<20:
    print(y)
    x,y = y,x+y

1
1
2
3
5
8
13


In [ ]:
for i in range(10):
    if(i%3 == 0):
        print("FIZZZZZ")
    elif(i%5 ==0 )  :
        print("BUZZ")
    elif(i%3 == 0) or (i%5 == 0):
        print("FIZZZBUZZZZ")
    else:
        print(i)

In [ ]:
#factorial of number

num = int(input('enter a string :'))
factorial = 1
if num<0:
    print("Factorial of negative numbers not possible")
elif num == 0:    
    print("Factorial of 0 is 1")
elif num>0:
    for i in range(1, num+1):
        factorial = factorial * i
print("The factorial of ", num, "is", factorial)        

In [2]:
string = input("Input the String->")
digit = letter = 0
for i in string:
    if i.isdigit():
         digit = digit+1
    elif i.isalpha():
        letter = letter+1
print("Letters in ", string, "is", letter)
print("Digits in", string, "is", digit)
        
       

Input the String->kmhtdw4
Letters in  kmhtdw4 is 6
Digits in kmhtdw4 is 1


In [ ]:
# TELSU
# FUNCTION IS A TASK WHICH WORKS WHEN WE CAL IT

print("komal's laptop")
print('komal\'s "laptop"') # backslash
10 * 'komal'

In [ ]:
# raw string : prints the string as it is
print(r'C\:DOC\NOW')

# variables : container to store values



In [ ]:
# underscore gives output of previous varaible
x,y = 2,3
x+y
_ +y

In [5]:
name = 'komal'
name + 'rocks'; # gives o/p in single string
name , 'rocks' #gives o/p in list
# strings are immutable i.e once assingned cant be modified

('komal', 'rocks')

# list

In [ ]:
name = [10,223,43,56,'komal']
# name[-5:-1]
# name.insert(2,'ria')
# name
# name.remove(10) ; name  # removes by name
# name.pop(1); name   #REMOVES BY INDEX
name.pop();name
# name.extend(['kia', 43, 45]) ; name
# name.sort()

# tuples

In [ ]:
# immutable
tup = (21,2,3,4,5,56)
tup[1]
#tup[1] = 2 #XXXXXXXXXXXXXX
tup.count



In [6]:
set1 = {21,2,3,4,5,6,5,5,6};set1
#sets work upon the hash concept hence increasing the speed
#also removes the repeated values; unique values fetch
#faster

{2, 3, 4, 5, 6, 21}

In [ ]:
s = {7,6,5,6,4,5,7};s
#s[1]    indexing not supported coz no sequence defined already
s.update() 

# Dictionary

In [8]:
# key value pair
# key should be unique and immuatable
data = {1:'komal', 2:'kiran', 4:'karan'};data

{1: 'komal', 2: 'kiran', 4: 'karan'}

In [9]:
data[4]

'karan'

In [11]:
data.get(1)
data.get(3)  #no error


{1: 'komal', 2: 'kiran', 4: 'karan'}

In [13]:
keys = ['komal','kiran','kiroon']

values = ['python','java', 'c']

In [14]:
# merge these two to form a dictionary
data = dict(zip(keys,values))
data

{'komal': 'python', 'kiran': 'java', 'kiroon': 'c'}

In [ ]:
# add another record
data['monika'] = 'c++'
data

In [ ]:
#delete
del data['kiroon'] # XXXXXXXXXXX error
data

In [15]:
lang = {'JS':'Atom', 'C':'Emulator', 
        'Python':{'Pycharm', 'Anaconda', 'Sublime'}, 
        'Java':{'JSE':'Netbeans', 'JEE':'Ecllipse'}
       }
lang
lang['JS']
lang['Python']
lang['Java']['JEE']


'Ecllipse'

In [15]:
def sum_mul(num1, num2):
 
    return [num1*num2  if(num1*num2) > 1000 else num1+num2]

number1 = int(input('Enter 1st number:'))
number2 = int(input('Enter 2nd number:'))
   
sum_mul(number1, number2)


Enter 1st number:10
Enter 2nd number:1


[11]

In [4]:
x, y = [int(x) for x in input("Enter two value: ").split()] 
print("First number is {} and second number is {}".format(x, y)) 
print() 

Enter two value: 2 3
First number is 2 and second number is 3



In [28]:
def iterat():
    prev = 0
    for i in range(11):
        sum = prev + i
        print('Current Number {}  Previous Number  {}  Sum: {} '.format(i,prev,sum))
        prev = i
iterat()

Current Number 0  Previous Number  0  Sum: 0 
Current Number 1  Previous Number  0  Sum: 1 
Current Number 2  Previous Number  1  Sum: 3 
Current Number 3  Previous Number  2  Sum: 5 
Current Number 4  Previous Number  3  Sum: 7 
Current Number 5  Previous Number  4  Sum: 9 
Current Number 6  Previous Number  5  Sum: 11 
Current Number 7  Previous Number  6  Sum: 13 
Current Number 8  Previous Number  7  Sum: 15 
Current Number 9  Previous Number  8  Sum: 17 
Current Number 10  Previous Number  9  Sum: 19 


In [22]:
def stringg(strr):
    for i in range(0, len(strr), 2):
        print('index[',i,']', (strr[i]) )
stringg('kokoko')        

index[ 0 ] k
index[ 2 ] k
index[ 4 ] k


In [33]:
def removeChars(strr, num):
    k = strr[num:]
    print(k.upper())
removeChars('havana', 3)        

ANA


In [44]:
def first_last(list1):
    if list1[0] == list1[-1]:
        return True
    return False
first_last([10,20,30,40,50])        

False

In [4]:
def mul_5(list1):
    for element in list1:
        if element % 5 == 0:
            print(element)
mul_5([10,5,31,25])            

10
5
25


In [9]:
def count1(stringg):
    cnt = stringg.count('Emma')
    print('Emma appears {} times : ' .format(cnt))
count1('Emma is good Emma')    

Emma appears 2 times : 


In [30]:
# for num in range(10):
#     print(num)
#     for i in range(num):
#         print(num, end = ' ')
# #         print(element)
# print('\n')
 
    
for num in range(10):
    for i in range(num):
        print (num, end=" ") #print number
    # new line after each row to display pattern correctly
    print("\n")    



1 

2 2 

3 3 3 

4 4 4 4 

5 5 5 5 5 

6 6 6 6 6 6 

7 7 7 7 7 7 7 

8 8 8 8 8 8 8 8 

9 9 9 9 9 9 9 9 9 



In [ ]:
n=int(input("Enter number: "))
rev=0
while(n>0):
    dig=n%10
    rev=rev*10+dig
    n=n//10
print("Reverse of the number:",rev)

In [ ]:
x  = [1,2,3]
k = []
for i in reversed(x):
    k.append(i)
print(k) #reverse for list

In [43]:
list1 = [1,2,9,4,6,5]
list2 = [9,7,8,4,3]
def fn(list1,list2):
    list3 = []
    for i in list1:
        if i%2 != 0:
            list3.append(i)
    for i in list2:
        if i%2 == 0:
            list3.append(i)
    return list3        
fn(list1,list2)

[1, 9, 5, 8, 4]

### I/P AND O/P

In [4]:
print('My', 'Name', 'Is', 'James', sep = '**')

My**Name**Is**James


In [6]:
print(round(375.94758748,2))

375.95


In [18]:
x,y,z = input('enter values:')
print('totalMoney {} \n quantity {} \n Price {} \n' .format(x,y,z))

enter values:234
totalMoney 2 
 quantity 3 
 Price 4 



In [ ]:
floatNumbers = []
n = int(input("Enter the list size : "))

print("\n")
for i in range(0, n):
    print("Enter number at location", i, ":")
    item = float(input())
    print(item)
    floatNumbers.append(item)
    
print("User List is ", floatNumbers)

Enter the list size : 3


Enter number at location 0 :
1
1.0
Enter number at location 1 :


In [26]:
import os
print(os.stat("test.txt").st_size == 0)
# file empty or not

False


In [23]:
floatList = []
n = int(input('The size of line is : '))
for i in range(n):
    print('enter the element at ', i, ' : ')
    item = float(input())
    floatList.append(item)
print('list  : ', floatList)    

The size of line is : 3
enter the element at  0  : 
1
enter the element at  1  : 
2
enter the element at  2  : 
3
list  :  [1.0, 2.0, 3.0]


In [4]:
with open('test.txt', 'r') as fp:
    line = fp.readlines()
    print(line[6])

line 4 



In [3]:
i = 1 
while i<11:
    print(i)
    i+=1

1
2
3
4
5
6
7
8
9
10


In [12]:
for row in range(1,6):
    for col in range(1,row+1):
        print(col, end = ' ')
    print(" ")    

1  
1 2  
1 2 3  
1 2 3 4  
1 2 3 4 5  


In [1]:
# n = int(input())
# i = 1
# while i<=10:
#     print((n*i))
#     i +=1
for i in range(1,11):
    print(2*i)

2
4
6
8
10
12
14
16
18
20


In [6]:
def mul_5(list1):
    new = []
    for i in list1:
        if (i>150):
             break
        if (i%5 == 0):
            new.append(i)
    return new         
mul_5([12, 15, 32, 42, 55, 75, 122, 132, 150, 180, 200])

[15, 55, 75, 150]

In [14]:
n = '1234'
for i in n.split(','):
    print(i)

1 2 3 4


In [19]:
num = 75869
count = 0
while num != 0:
    num //= 10
#     print(num)
    count+= 1
print("Total digits are: ", count)

print(len(str(abs(-1234))))

Total digits are:  5
4


In [12]:
list1 = [10, 20, 30, 40, 50, 60]
start = len(list1) -1
stop = -1
step = -1
for i in range(start, stop, step):
    print(list1[i])    

5
60
50
40
30
20
10


In [22]:
for i in  range(-10, 0):
    print(i)
print('Done!!!')    

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1
Done!!!


In [4]:
x = 0
temp = 0
while x<=10:
    temp = temp+x
    x +=1
    
print(temp)    

55


In [11]:
def getMiddleThreeChars(stringg):
    
    middleIndex = int(len(stringg) /2)
    mid_letter = stringg[middleIndex]
    
    print(middleIndex,mid_letter)
    print('Original string is {}'.format(stringg))
   
    middleThree = stringg[middleIndex-1 : middleIndex+2]
    print('Middle values are : {}'.format(middleThree))
    
getMiddleThreeChars("JhonDipPeta")
getMiddleThreeChars("Jasonay") 

5 i
Original string is JhonDipPeta
Middle values are : Dip
3 o
Original string is Jasonay
Middle values are : son


In [42]:
def appendMiddle(s1,s2):
    mid = int(len(s1)/2) -1
#     print(s1[mid])
    print('Original strings are: "{}" and "{}"'.format(s1,s2))
    ad = s1[:mid]
    ad2 = s1[mid:]
#     print(ad)
    new = ad + s2
    new = new + ad2
    print("New string after appending '{}'".format(new))
appendMiddle("Chrisdem", 'IamNewString') #→ "ChrIamNewStringisdem"()9


#  middleThree = s1[:middleIndex-1:]+ s2 +s1[middleIndex-1:]

Original strings are: "Chrisdem" and "IamNewString"
New string after appending 'ChrIamNewStringisdem'


In [46]:
def mixString(s1, s2):
    
#     mid_s1 = int(len(s1)/2)
#     mid_s2 = int(len(s2)/2)
    
    first = s1[:1] + s2[:1] + s1[int(len(s1)/2)] + s2[int(len(s2)/2)] + s1[-1:] + s2[-1:] 
    
    print(first)

mixString("America", "Japan")# = ""AJrpan"

AJrpan


In [9]:
def lower1(stringg):
    lower = []
    upper = []
    for i in stringg:
        if i.islower():
            lower.append(i)
        else:
            upper.append(i)
    print(''.join(lower+upper))        
lower1('KOmal')    

malKO


In [64]:
x = 'komal'
print(list(x))

['k', 'o', 'm', 'a', 'l']


In [81]:
input_str = "k@#yn26At^&i5Ve"
count1 = 0
count2 = 0
count3 = 0
count4 = 0
for i in input_str:
    if i.isupper():
        count1 +=1
    elif i.islower():
        count2 +=1
    elif i.isnumeric():
        count3 += 1
    else:
        count4 +=1
        
        
print('upper : {} lower : {} digits : {} spl.symbols : {}'.format(count1, count2, count3, count4))        


upper : 2 lower : 6 digits : 3 spl.symbols : 4


In [34]:
def mixedString(s1, s2):
    result = ""
    
    s2 = s2[::-1]
#     print(s2)
#     s1 = list(s1)
#     s2 = list(s2)
#     result = list(zip(s1,s2))
#     result = str(result)
#     print(''.join(result))
    
    for i in range(10):
        if (len(s1)>i):
            result = result + s1[i]
#             print(result)
        if(len(s2)>i):
            result = result + s2[i]
#             print(result)
    print(result)
    
    
    
mixedString('komal', 'vatsalvali')    

kiolmaavllastav


In [18]:
def mixString(s1, s2):
    
    s2 = s2[::-1]
    lengthS1 = len(s1)
    lengthS2 = len(s2)
    length  = lengthS1 if lengthS1 > lengthS2 else lengthS2 
    resultString=""
    for i in range(length):
#         if(i < lengthS1):
#               resultString = resultString + s1[i]
#               print(resultString)  
        if(i < lengthS2):
              resultString = resultString + s2[i]
    
    print(resultString)
  
s1 = "Pynative"
s2 = "Websiteeee"
mixString(s1, s2)

eeeetisbeW


In [37]:
def strBalance(s1, s2):
    if s1 in s2:
        return True
strBalance('mo', 'komal')    

In [46]:
def stringBalanceCheck(s1, s2):
    for char in s1:
        if char in s2:
            flag = True

        else:
              flag =  False
    return flag
  
s1 = "tez"
s2 = "Pynative"
flag = stringBalanceCheck(s1, s2)
print("s1 and s2 are balanced", flag)


s1 and s2 are balanced False


In [53]:
def occ(stringg):
    temp_str = stringg.lower()
#     print(temp_str)
    count1 = temp_str.count('usa')
    return count1
count1 = occ('USA is awesome, usa is love, USa is fun')
print('The no.of USA occurance is {}'.format(count1))

The no.of USA occurance is 3


In [56]:
def sumAndAverage(stringg):
    sum1 = 0
    aveRAGE = 0
    for i in stringg:
        if i.isnumeric():
            print(i)
            sum1 = sum1 + i
            average1 = average1 + i
    return sum1, average1
sum1, average1 = sumAndAverage("English = 78 Science = 83 Math = 68 History = 65") #= sum 294 Percentage is 73.5
print('SUM : {} , AVERAGE : {}'.format(sum1, average1))

7


TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [60]:
strr = 'jai maha kali mahakali ki jai ho'
count_dict = dict()
for char in strr:
    count = strr.count(char)
#     print(count)
    
    count_dict[char] = count
print(count_dict)    

{'j': 2, 'a': 8, 'i': 5, ' ': 7, 'm': 2, 'h': 3, 'k': 3, 'l': 2, 'o': 1}


In [14]:
import numpy as np
first_array = np.empty([4,2], dtype = np.uint16)    #uint16, uint32
shape1 = np.shape(first_array)
dim1 = np.ndim(first_array)
size1 = np.size(first_array)
display(first_array, shape1, dim1, size1)

array([[15783, 18142],
       [37735, 22409],
       [61599, 58017],
       [54015, 52138]], dtype=uint16)

(4, 2)

2

8

In [17]:
np.arange(100, 200, 10).reshape(5,2)

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [26]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
sampleArray
# np.ndim(sampleArray)
sampleArray[[0,1,2],[1,1,1]]


array([22, 55, 88])

In [38]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print(sampleArray)
sampleArray[::2, 1::2]


[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]


array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [39]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
sum1 = (arrayOne + arrayTwo)**2
sum1

array([[ 400, 1521, 1089],
       [ 625,  625,  784]], dtype=int32)

In [42]:
array1 = np.arange(10,34).reshape(8,3)
subArray  = np.split(array1, 4)
display(array1, subArray)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

In [48]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
np.sort(sampleArray)[2]
sortArrayByRow = sampleArray[:,sampleArray[1,:].argsort()]
display(sampleArray, sortArrayByRow )

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

array([[73, 43, 34],
       [12, 22, 82],
       [66, 94, 53]])

In [2]:
alist = [100,200,300,400,500]
alist[::-1]

[500, 400, 300, 200, 100]

In [4]:
list1 = ["M", "na", "i", "Ke"] 
list2 = ["y", "me", "s", "lly"]
[(i+j) for i,j in zip(list1,list2)]
# list(zip(list1,list2))

['My', 'name', 'is', 'Kelly']

In [8]:
aList = [1, 2, 3, 4, 5, 6, 7]
[i**2 for i in aList]

[1, 4, 9, 16, 25, 36, 49]

In [9]:
list1 = ["Hello ", "take "]
list2 = ["Dear", "Sir"]
list(zip(list1,list2))

[('Hello ', 'Dear'), ('take ', 'Sir')]

In [21]:
list1 = [10, 20, 30, 40]
list2 = [100, 200, 300, 400]
list2 = list2[::-1]
for i,j in zip(list1,list2):
    print(i,j) 

10 400
20 300
30 200
40 100


In [28]:
list1 = ["Mike", "", "Emma", "Kelly", "", "Brad"]
# [ i for i in list1 if i != '']

res = list(filter(None, list1))
print(res)

['Mike', 'Emma', 'Kelly', 'Brad']


In [38]:
list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
list1[2][2].append(7000)
print(list1)

[10, 20, [300, 400, [5000, 6000, 7000], 500], 30, 40]


In [58]:
list1 = ["a", "b", ["c", ["d", "e", ["f", "g"], "k"], "l"], "m", "n"]
sub =['h','i','j']
list1[2][1][2].extend(sub)
print(list1)

['a', 'b', ['c', ['d', 'e', ['f', 'g', 'h', 'i', 'j'], 'k'], 'l'], 'm', 'n']


In [84]:
list1 = [5, 10, 15, 20, 25, 50, 20]
x = list1.index(20)
list1[x] = 200;list1

[5, 10, 15, 200, 25, 50, 20]

In [93]:
list1 = [5, 20, 15, 20, 25, 50, 20]
result = list(filter(lambda x: x!=20, list1))
print(result)


[5, 15, 25, 50]


In [98]:
dict1 = {'Ten': 10, 'Twenty': 20, 'Thirty': 30}
dict2 = {'Thirty': 30, 'Fourty': 40, 'Fifty': 50}

dict3 = {**dict1, **dict2}
print(dict3)

# dict3 = dict1.copy()
# dict3.update(dict2)
# print(dict3)

{'Ten': 10, 'Twenty': 20, 'Thirty': 30, 'Fourty': 40, 'Fifty': 50}


In [101]:
keys = ['Ten', 'Twenty', 'Thirty']
values = [10, 20, 30]
dict1 = dict(zip(keys,values))
print(dict1)

{'Ten': 10, 'Twenty': 20, 'Thirty': 30}


In [104]:
sampleDict = { 
   "class":{ 
      "student":{ 
         "name":"Mike",
         "marks":{ 
            "physics":70,
            "history":80
         }
      }
   }
}

sampleDict['class']['student']['marks']['history']

80

In [4]:
employees = {'Kelly', 'Emma', 'John'}
defaults = {"designation": 'Application Developer', "salary": 8000}

resDict = dict.fromkeys(employees, defaults)
print(resDict)

# Individual data
print(resDict["Kelly"])

{'John': {'designation': 'Application Developer', 'salary': 8000}, 'Kelly': {'designation': 'Application Developer', 'salary': 8000}, 'Emma': {'designation': 'Application Developer', 'salary': 8000}}
{'designation': 'Application Developer', 'salary': 8000}


In [9]:
sampleDict = {
  "name": "Kelly",
  "age":25,
  "salary": 8000,
  "city": "New york" 
  
}

keys = ["name", "salary"]
{k: sampleDict[k] for k in keys}

{'name': 'Kelly', 'salary': 8000}

In [12]:
sampleDict = {
  "name": "Kelly",
  "age":25,
  "salary": 8000,
  "city": "New york"
  
}
keysToRemove = ["name", "salary"]
{k : sampleDict[k] for k in sampleDict.keys() - keysToRemove}

{'age': 25, 'city': 'New york'}

In [18]:
sampleDict = {'a': 100, 'b': 200, 'c': 300}
200 in sampleDict.values()

True

In [22]:
sampleDict = {
  "name": "Kelly",
  "age":25,
  "salary": 8000,
  "city": "New york"
  
}
sampleDict['location'] = sampleDict.pop('city')
sampleDict
sampleDict['location'] = 'Downtown'; sampleDict

{'name': 'Kelly', 'age': 25, 'salary': 8000, 'location': 'Downtown'}

In [24]:
sampleDict = {
  'Physics': 82,
  'Math': 65,
  'history': 75
}
min(sampleDict.items())

('Math', 65)

In [6]:
sampleDict = {
     'emp1': {'name': 'Jhon', 'salary': 7500},
     'emp2': {'name': 'Emma', 'salary': 8000},
     'emp3': {'name': 'Brad', 'salary': 6500}
}

sampleDict['emp3']['salary']  = 8500 ; sampleDict
# sampleDict['emp3']['naaam'] = sampleDict.pop('name');sampleDict
sampleDict['emp3']['name'] = sampleDict['emp3']['naam']

KeyError: 'naam'

In [38]:
sampleSet = {"Yellow", "Orange", "Black"}
sampleList = ["Blue", "Green", "Red"]
# sampleList = set(sampleList)
sampleSet.update(sampleList)
sampleSet

{'Black', 'Blue', 'Green', 'Orange', 'Red', 'Yellow'}

In [45]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}
set1.intersection(set2)

{30, 40, 50}

In [47]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}
set1.union(set2)

{10, 20, 30, 40, 50, 60, 70}

In [50]:
set1 = {10, 20, 30}
set2 = {20, 40, 50}
set1 - set2

{10, 30}

In [52]:
set1 = {10, 20, 30, 40, 50}
set1.difference({10,20,30})


{40, 50}

In [55]:
set1 = {10, 20, 30, 40, 50}
set2 = {60, 70, 80, 90, 10}
set1.isdisjoint(set2)

False

In [59]:
set1 = {10, 20, 30, 40, 50}
set2 = {60, 70, 80, 90, 10}    
set1.isdisjoint(set2)    

False

In [64]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}
set2 = set2-set1
set1.update(set2)
set1

{10, 20, 30, 40, 50, 60, 70}

In [3]:
limit=int(input('Enter the limit to check'))
pythogareoustriplets=[(x,y,z) for x in range(1,limit) for y in range(x,limit) for z in range(y,limit) if (x*x)+(y*y)==(z*z)]
print(pythogareoustriplets)

Enter the limit to check50
[(3, 4, 5), (5, 12, 13), (6, 8, 10), (7, 24, 25), (8, 15, 17), (9, 12, 15), (9, 40, 41), (10, 24, 26), (12, 16, 20), (12, 35, 37), (15, 20, 25), (15, 36, 39), (16, 30, 34), (18, 24, 30), (20, 21, 29), (21, 28, 35), (24, 32, 40), (27, 36, 45)]


In [12]:
# The single star * unpacks the sequence/collection into positional arguments
n = int(input())
print(*range(1, n + 1), sep = '')

3
123


In [15]:
if __name__ == '__main__':
    n = int(input())
    student_marks = {}

    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()

    if query_name in student_marks:
        x = ((float(student_marks[query_name][0]) + 
           float(student_marks[query_name][1]) + 
           float(student_marks[query_name][2])) / 3)

    print('%.2f' %x)



2
komal 23 43 44.4 
kiz 34 54 56.6
komal
36.80
